name: Hello World Workflow

on: 
  push:
    branches:
      - main  # Run only when code is pushed to main branch

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Pulls your repo into the runner

      - name: Print greeting
        run: echo "Hello from GitHub Actions 🚀"
